---
driver:
  name: vagrant

provisioner:
  name: shell

platforms:
  - name: tfcustom-bionic
    driver:
      box: tfcustom-bionic
      provider: virtualbox

verifier:
  name: inspec

suites:
  - name: default
